oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    path: /profile